#!/usr/bin/env python3
import klib
import getpass
import argparse


def nameOrID():
	while "the answer is invalid":
		reply = str(input("quizName or quizID? [n/i] > ")).lower().strip()
		if reply[:1] == 'n':
			return True
		if reply[:1] == 'i':
			return False


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument('-e', "--email", help="The email used to login to create.kahoot.it")
	parser.add_argument('-a', "--password", help="The corresponding password used to login to create.kahoot.it")
	parser.add_argument('-n', "--name", help="The nickname to join the kahoot with")
	parser.add_argument('-p', "--pin", help="The game pin")
	parser.add_argument('-q', "--quizName", help="The quiz's name")
	parser.add_argument('-I', "--quizID", help="The quiz's ID")
	args = parser.parse_args()
	email = args.email
	password = args.password
	name = args.name
	pin = args.pin
	quizID = args.quizName
	quizName = args.quizID

	try:
		if not name:
			name = input('name > ')
		if not pin:
			pin = input('pin > ')
		if quizName and email and password:
			user = klib.Kahoot(pin, name, quizName=quizName)
		elif quizName:
			print('Authentication required when searching for quizzes by name')
			exit()
		elif quizID:
			user = klib.Kahoot(pin, name, quizID=quizID)
		else:
			if email and password:
				if nameOrID():
					quizName = input('quizName > ')
					user = klib.Kahoot(pin, name, quizName=quizName)
				else:
					quizID = input('quizID > ')
					user = klib.Kahoot(pin, name, quizID=quizID)
			else:
				quizID = input('quizID > ')
				user = klib.Kahoot(pin, name, quizID=quizID)
		if email and password:
			user.authenticate(email, password)
		user.checkPin()
		user.startGame()
	except KeyboardInterrupt:
		print('EXITING...')
		exit()
