#!/usr/bin/env python3
import grab
import sys

USAGE = '''
kbot GAMEID (GAMEPIN) (USERNAME)
'''
EMAIL = "kahootbot27@gmail.com"
PASSWORD = "appropriatesigmajamiemonkeyalongheat"
name = "jimmy"
if len(sys.argv) == 4:
    name = sys.argv[3]

if len(sys.argv) >= 3:
    answers = grab.scrape(sys.argv[1],EMAIL,PASSWORD)
    print('Answers received')
    grab.start_bot(sys.argv[2],name,answers)
elif len(sys.argv) == 2:
    grab.printAnswers(sys.argv[1],EMAIL,PASSWORD)
else:
    print(USAGE)
